name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Paso 1 - Checkout del repositorio
      - name: Checkout repo
        uses: actions/checkout@v3

      # Paso 2 - Configurar Node.js
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check Node and npm version
        run: |
          node -v
          npm -v

      # Paso 3 - Instalación limpia de dependencias
      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      # Paso 4 - Construir el proyecto
      - name: Build project
        run: npm run build

      # Paso 5 - Subir archivos listos para producción
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      # Paso 6 - Descargar los archivos de producción
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      # Paso 7 - Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
